const COLOR_GRAY = "#21262d";
const COLOR_GRAY_HIGHLIGHT = "#49515c";
const COLOR_BLUE = "#3f84e4";
const COLOR_BLACK = "#0d1117";
const COLOR_WHITE = "#DBE3E3";
const COLOR_RED = "#f78166";
const COLOR_LIGHT_GRAY = "#93989e";
const COLOR_GREEN = "#41f064";

export {
  COLOR_GRAY,
  COLOR_GRAY_HIGHLIGHT,
  COLOR_BLUE,
  COLOR_BLACK,
  COLOR_WHITE,
  COLOR_RED,
  COLOR_LIGHT_GRAY,
  COLOR_GREEN,
};
